### ISSUE TITLE
Inject metadata into data stream

### ISSUE THREAD

**Issue by pekasen** [Leibniz-HBI/dabapush#83]
This will allow users to configure additional data into the data stream via the configuration.

## Use Case

Consider for instance adding a column `file` to the data stream in order to re-capture  identifiers that are embedded into the file name, i.e. `123494328.csv`.

Configuration semantics for this would look like this:

```yaml
 bigquery: !dabapush_gbq:GBQWriterConfiguration
    auth_file: XXX
    chunk_size: 20000
    dataset_name: XX
    id: e108c2a5-c458-4e7a-a37d-182f546db6fe
    name: bigquery
    scratch_location: memory
    project_name: XX
    schema_file: schema_test.json
    table_name: posts
    additional_columns:
        file: record.parent.id.stem  # Access the records's
        # parent's id (which is a Path in this example)
        # and access the `stem` field.
```

## Allowed Values

- Any constant that will inserted as is.
- Any field or value attached to the record (except the payload).
